name: Build & Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: false
        type: string
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - ".github/**"
      - "docs/**"
      - "**.md"

env:
  DOCKERHUB_SLUG: docker.io/yucatovo/grokcf
  GHCR_SLUG: ghcr.io/yucat-ovo/grokcf

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker Meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
            ${{ env.GHCR_SLUG }}
          tags: |
            type=ref,event=branch,enable=${{ github.ref_name != github.event.repository.default_branch }}
            type=edge,branch=develop
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            type=sha
          labels: |
            org.opencontainers.image.title=GrokCF
            org.opencontainers.image.description=GrokCF.
            org.opencontainers.image.vendor=YuCat-OVO

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: "--debug"
          platform: linux/amd64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
